# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build SongodaCore

on:
  push:
    branches: [ master, development ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Setup Java
      - uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: adopt

      # Checkout project files
      - uses: actions/checkout@v2

      # Caches
      - name: 'Cache: Maven'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # Build project
      - name: Build with Maven
        run: 'mvn -B -Duser.name="GitHub Runner on $GITHUB_REPOSITORY (id=$GITHUB_RUN_ID)" clean package'

      # Upload build artifacts
      - name: 'Upload Build Artifact: SongodaCore-*.jar'
        uses: actions/upload-artifact@v2
        with:
          name: EpicAnchors-artifacts
          path: ./Core/target/SongodaCore-*.jar
